sudo: required

services:
  - docker

env:
  matrix:
     - DOCKERFILE="2.8"
     - DOCKERFILE="3.0"
     - DOCKERFILE="3.2"

before_script:
  - docker version

script:
  - docker build -t ${DOCKERFILE} ./${DOCKERFILE}

after_script:
  - docker images
